---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: piraeus-datastore

resources:
  - namespace.yaml
  - https://github.com/piraeusdatastore/piraeus-operator/config/default?ref=v2.8.1
