---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: piraeus-datastore
resources:
  - https://github.com/piraeusdatastore/piraeus-operator/config/default?ref=v2.9.0
  # - linstor-repository.yaml
  # - linstor-release.yaml
