apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linstor-affinity-controller
  namespace: piraeus-datastore
spec:
  interval: 5m
  chart:
    spec:
      chart: linstor-affinity-controller
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: linstor
        namespace: piraeus-datastore
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  values:
    replicaCount: 3
