apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
data:
  ADGUARD_0_HOST: adguard-home.adguard-home.svc.cluster.local
  ADGUARD_0_PORT: "80"
  ADGUARD_0_URL: http://adguard-home.adguard-home.svc.cluster.local
  ADGUARD_0_WEB_URL: https://adguard.clsn.dev
  
  ADGUARD_1_HOST: 192.168.95.11
  ADGUARD_1_PORT: "3000"
  ADGUARD_1_URL: http://192.168.95.11:3000
  ADGUARD_1_WEB_URL: https://adguard-01.clsn.dev
  
  ADGUARD_2_HOST: 192.168.95.12
  ADGUARD_2_PORT: "3000"
  ADGUARD_2_URL: http://192.168.95.12:3000
  ADGUARD_2_WEB_URL: https://adguard-02.clsn.dev
  
  ADGUARD_3_HOST: 192.168.95.13
  ADGUARD_3_PORT: "3000"
  ADGUARD_3_URL: http://192.168.95.13:3000
  ADGUARD_3_WEB_URL: https://adguard-03.clsn.dev
