apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars-secret
    namespace: flux-system
type: Opaque
stringData:
    PLACE: ENC[AES256_GCM,data:4ZGBgx1M,iv:fH0vzwVCS3Ajej/0/BwSWsdTiPjSCOz2SI5Bi2COSdQ=,tag:5CKUVdFNsyWu/7oqYqqK/g==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcGtuMGVHNnQwemhzejhq
            TEhSblZJaUdYejdiNHRHVWtFSVpaQUt2anhnCm5NR2J5NzlYMThOaVVlRmUrdlda
            Nkh3UmU3QUVSUlZIOTVxZ1dzVlhHcGMKLS0tIEc2TlBpWkV4M1NOWmpFMlRNNEl3
            cFZIT3FCcHJhbm9BV0grajlDWWtzRmcKmurTuT6u6GShtUhH7nulvZ+SSk+jE8lq
            VKHVRE3ZMu6YcPSIP7y9nb9K7lvqBLIsBFy7aQVZAvfLKj9JRIHyJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-24T16:03:33Z"
    mac: ENC[AES256_GCM,data:YIpq3QRzGPiPSJl5rSp75MJeOkr/6JGHWfU+Cl8pnDZD53hpr25Ap6NwjUYHDfnGO+vAIAWy/YLbR7heSrSUQPeRkM4rMQSokuvUzD6s3HPApDEeViYD6m7goWTQO/12o0qDT2CDXsMb5EWRmtM9POcZx6QlLGUlSRUjFxNzBGw=,iv:X40PRd/S6y7G8HOiSSxgyW9CX6MkmAs/u44KX3TMzxE=,tag:6ktV0H7MtLXEISEPFypCog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
