---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kuma-ingress-watcher
  namespace: kuma
spec:
  interval: 5m
  timeout: 2m
  chart:
    spec:
      chart: kuma-ingress-watcher
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: kuma-ingress-watcher
  values:
    namespace: kuma
    secret:
      name: kuma-ingress-discovery-token
    deployment:
      name: kuma-ingress-watcher
      replicas: 1
      label: kuma-ingress-watcher
      image:
        name: ghcr.io/squent/kuma-ingress-watcher
      logLevel: INFO
    uptimeKuma:
      url: "https://status.clsn.dev"
      credentialsSecret: uptime-kuma-secret
