apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: template-exporter-secret
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: adguard-home-kubernetes-secret-store
    kind: SecretStore
  target:
    name: adguard-home-exporter-secret
    template:
      engineVersion: v2
      data:
        ADGUARD_SERVERS: ${ADGUARD_0_URL},${ADGUARD_1_URL},${ADGUARD_2_URL},${ADGUARD_3_URL}
        ADGUARD_USERNAMES: '{{ .user0 }},{{ .user1 }},{{ .user2 }},{{ .user3 }}'
        ADGUARD_PASSWORDS: '{{ .password0 }},{{ .password1 }},{{ .password2 }},{{ .password3 }}'
        INTERVAL: 15s
  data:
  - secretKey: user0
    remoteRef:
      key: adguard-home-sync-secret
      property: ORIGIN_USERNAME
  - secretKey: password0
    remoteRef:
      key: adguard-home-sync-secret
      property: ORIGIN_PASSWORD
  - secretKey: user1
    remoteRef:
      key: adguard-home-sync-secret
      property: REPLICA1_USERNAME
  - secretKey: password1
    remoteRef:
      key: adguard-home-sync-secret
      property: REPLICA1_PASSWORD
  - secretKey: user2
    remoteRef:
      key: adguard-home-sync-secret
      property: REPLICA2_USERNAME
  - secretKey: password2
    remoteRef:
      key: adguard-home-sync-secret
      property: REPLICA2_PASSWORD
  - secretKey: user3
    remoteRef:
      key: adguard-home-sync-secret
      property: REPLICA3_USERNAME
  - secretKey: password3
    remoteRef:
      key: adguard-home-sync-secret
      property: REPLICA3_PASSWORD
