---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adguard-home
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - sync-secret.yaml
  - release-sync.yaml
