---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home-sync
  namespace: adguard-home
spec:
  interval: 5m
  timeout: 2m
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/bakito/adguardhome-sync
              # renovate datasource=docker depName=ghcr.io/bakito/adguardhome-sync
              tag: v0.7.8
            args:
              - run
            env:
              TZ: "Europe/Berlin"
              CRON: "*/1 * * * *"
              FEATURES_CLIENT_SETTINGS: true
              FEATURES_DHCP_SERVER_CONFIG: true
              FEATURES_DHCP_STATIC_LEASES: true
              FEATURES_DNS_ACCESS_LISTS: true
              FEATURES_DNS_REWRITES: true
              FEATURES_DNS_SERVER_CONFIG: true
              FEATURES_FILTERS: true
              FEATURES_GENERAL_SETTINGS: true
              FEATURES_QUERY_LOG_CONFIG: true
              FEATURES_SERVICES: true
              FEATURES_STATS_CONFIG: true
              FEATURES_THEME: true
              API_DARK_MODE: true
              ORIGIN_URL: ${ADGUARD_0_URL}
              ORIGIN_WEB_URL: ${ADGUARD_0_WEB_URL}
              RUN_ON_START: true
              REPLICA1_AUTO_SETUP: true
              REPLICA1_URL: ${ADGUARD_1_URL}
              REPLICA1_WEB_URL: ${ADGUARD_1_WEB_URL}
              REPLICA2_AUTO_SETUP: true
              REPLICA2_URL: ${ADGUARD_2_URL}
              REPLICA2_WEB_URL: ${ADGUARD_2_WEB_URL}
              REPLICA3_AUTO_SETUP: true
              REPLICA3_URL: ${ADGUARD_3_URL}
              REPLICA3_WEB_URL: ${ADGUARD_3_WEB_URL}
            envFrom:
              - secretRef:
                  name: adguard-home-sync-secret
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: &ingressClass traefik-internal
        annotations:
          kubernetes.io/ingress.class: *ingressClass
          uptime-kuma.autodiscovery.probe.name: "AdGuard Home Sync"
        hosts:
          - host: adguard-sync.clsn.dev
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
