---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-exporter
  namespace: adguard-home
spec:
  interval: 5m
  timeout: 2m
  chart:
    spec:
      chart: app-template
      version: 15.4.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    TZ: "Europe/Berlin"
    image:
      repository: ghcr.io/henrywhitaker3/adguard-exporter
      # renovate datasource=docker depName=ghcr.io/henrywhitaker3/adguard-exporter
      tag: v1.2.0
      pullPolicy: IfNotPresent

    workload:
      main:
        podSpec:
          containers:
            main:
              probes:
                liveness:
                  path: /healthz
                readiness:
                  path: /readyz
                startup:
                  path: /readyz
              envFrom:
                - secretRef:
                    name: adguard-home-exporter-secret
                    expandObjectName: false

    service:
      main:
        enabled: true
        ports:
          main:
            protocol: http
            port: 9618
    metrics:
      main:
        enabled: true
        type: "servicemonitor"
        endpoints:
          - port: main
            path: /metrics
        targetSelector: main
        prometheusRule:
          enabled: false
