---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: adguard-home
spec:
  interval: 5m
  timeout: 2m
  chart:
    spec:
      chart: adguard-home
      version: "0.3.25"
      sourceRef:
        kind: HelmRepository
        name: adguard-home
  values:
    image:
      tag: v0.107.63
    env:
      TZ: "Europe/Berlin"
    service:
      main:
        ports:
          http:
            port: 80
    dns-tcp:
      type: LoadBalancer
      loadBalancerIP: "192.168.95.20"
      annotations:
        metallb.io/loadBalancerIPs: 192.168.95.20
        metallb.io/allow-shared-ip: adguard-home
    dns-udp:
      type: LoadBalancer
      loadBalancerIP: "192.168.95.20"
      annotations:
        metallb.io/loadBalancerIPs: 192.168.95.20
        metallb.io/allow-shared-ip: adguard-home
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik-internal
          # traefik.ingress.kubernetes.io/router.entrypoints: websecure
          # traefik.ingress.kubernetes.io/router.tls: "true"
          # traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt-prod
        hosts:
          - host: adguard.clsn.dev
            paths:
              - path: /
        # tls:
          # enabled: true
          # secretName: adguard-home-tls
    persistence:
      config:
        enabled: true
        storageClass: "ssd-perf-r3"
        accessMode: ReadWriteOnce
        size: 100Mi
      data:
        enabled: true
        storageClass: "ssd-perf-r3"
        accessMode: ReadWriteOnce
        size: 4Gi
      