---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home-sync
  namespace: adguard-home
spec:
  interval: 15m
  chart:
    spec:
      chart: adguardhome-sync
      version: 9.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        ports:
          main:
            port: 8080
            protocol: http
            targetPort: 8080
    ingress:
      main:
        primary: true
        annotations:
          kubernetes.io/ingress.class: traefik-internal
        hosts:
          - host: adguard-sync.clsn.dev
            paths:
              - path: /
    workload:
      main:
        podSpec:
          containers:
            main:
              args:
                - run
              env:
                CRON: "*/1 * * * *"
                FEATURES_CLIENT_SETTINGS: true
                FEATURES_DHCP_SERVER_CONFIG: true
                FEATURES_DHCP_STATIC_LEASES: true
                FEATURES_DNS_ACCESS_LISTS: true
                FEATURES_DNS_REWRITES: true
                FEATURES_DNS_SERVER_CONFIG: true
                FEATURES_FILTERS: true
                FEATURES_GENERAL_SETTINGS: true
                FEATURES_QUERY_LOG_CONFIG: true
                FEATURES_SERVICES: true
                FEATURES_STATS_CONFIG: true
                FEATURES_THEME: true
                API_DARK_MODE: true
                ORIGIN_URL: https://adguard.clsn.dev
                RUN_ON_START: true
                REPLICA1_AUTO_SETUP: true
                REPLICA1_URL: http://192.168.95.11:3000
                REPLICA1_WEB_URL: https://adguard-01.clsn.dev
                REPLICA2_AUTO_SETUP: true
                REPLICA2_URL: http://192.168.95.12:3000
                REPLICA2_WEB_URL: https://adguard-02.clsn.dev
                REPLICA3_AUTO_SETUP: true
                REPLICA3_URL: http://192.168.95.13:3000
                REPLICA3_WEB_URL: https://adguard-03.clsn.dev
