---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: adguard-home
  namespace: adguard-home
spec:
  url: oci://ghcr.io/gabe565/charts/adguard-home
  interval: 5m0s
  ref:
    tag: latest
    