---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: s3-operator
  namespace: minio
spec:
  interval: 5m
  timeout: 2m
  chart:
    spec:
      chart: s3-operator
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: inseefrlab
  values:
    crds:
      # -- Install and upgrade CRDs
      install: true
      # -- Keep CRDs on chart uninstall
      keep: true

    controllerManager:
      manager:
        image:
          repository: inseefrlab/s3-operator
          tag: v0.11.0
      replicas: 1
    kubernetesClusterDomain: cluster.local

    s3:
      endpointUrl: "minio.minio.svc.cluster.local:9000"

      # To manage access/secret keys, two options :
      #   - (Poor) Directly set them using the accessKey/secretKey parameters below.
      #   This makes them directly visible to anyone with enough rights on your k8s.
      #   - (Better) Use the existingSecret parameter to reference a k8s secret, which
      #   needs to contain at least two environment variables : S3_ACCESS_KEY and S3_SECRET_KEY.
      #   This in turn allows you to use another mechanism to further protect these,
      #   eg sealed secrets.
      existingSecret: "minio-s3-operator-secret"

      # Should the operator try to delete the resource from the S3 backend upon CR deletion ?
      deletion:
        bucket: false
        path: false
        policy: true
        s3user: true

      s3user:
        overrideExistingSecret: true
            
