apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: internal-services
resources:
- namespace.yaml
- servers-transport.yaml
- ./pve/pve.yaml
- ./homeassistant/homeassistant.yaml
- ./adguard/adguard-01.yaml
- ./adguard/adguard-02.yaml
- ./adguard/adguard-03.yaml
- ./uptime-kuma/uptime-kuma.yaml
