---
# Renovate Types
- name: renovate/container
  color: "027fa0"
- name: renovate/github-action
  color: "027fa0"
- name: renovate/grafana-dashboard
  color: "027fa0"
- name: renovate/github-release
  color: "027fa0"
- name: renovate/helm
  color: "027fa0"
# Semantic Types
- name: type/digest
  color: "ffeC19"
- name: type/patch
  color: "ffeC19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"
# retained defaults
- name: bug
  color: "#d73a4a"
- name: duplicate
  color: "#cfd3d7"
- name: enhancement
  color: "#a2eeef"
- name: invalid
  color: "#e4e669"
- name: question
  color: "#d876e3"
- name: wontfix
  color: "#ffffff"
