---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-configs
  namespace: flux-system  
spec:
  path: ./infrastructure/configs/metallb/metallb-configs
  targetNamespace: metallb-system
  interval: 10m
  prune: true
  dependsOn:
    - name: metallb-app
  sourceRef:
    kind: GitRepository
    name: flux-system