---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2-advertisment-tcpl-pxe
  namespace: metallb
spec:
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: tcpl-01
  - matchLabels:
      kubernetes.io/hostname: tcpl-02
  - matchLabels:
      kubernetes.io/hostname: tcpl-03
  ipAddressPools:
  - metallb-pool
  interfaces:
  - ens18
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2-advertisment-tworker-rp4b
  namespace: metallb
spec:
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: tworker-01
  - matchLabels:
      kubernetes.io/hostname: tworker-02
  ipAddressPools:
  - metallb-pool
  interfaces:
  - end0.95
