---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  interval: 10m
  chart:
    spec:
      chart: mongodb-kubernetes
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: mongodb
  timeout: 5m
  install:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  values:
    operator:
      watchNamespace: "*"
      nodeSelector:
        beta.kubernetes.io/arch: amd64
