apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
spec:
  certificates:
    - secretName: clsn-dev-tls
    - secretName: clsn-cloud-tls
  defaultCertificate:
    secretName: clsn-dev-tls