apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: grafana
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:YwUeEoI=,iv:Zaj+xKXsmNNnvqI5bkQKJfw54ddD9PHyRqNyaIqTreU=,tag:vpICfdgL6Tf8DRh9udF9aA==,type:str]
    password: ENC[AES256_GCM,data:m3mvoHl8YPEwsfVyYpFTlEIAm2icSNuFZwSIVkNwT0Bg,iv:XyHGFutIPZQ47N1RiVNf5Vw3LMAi41ExICeJNjQdhG0=,tag:xDKs0m3y4BMKfN7k/IxbAw==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcGtuMGVHNnQwemhzejhq
            TEhSblZJaUdYejdiNHRHVWtFSVpaQUt2anhnCm5NR2J5NzlYMThOaVVlRmUrdlda
            Nkh3UmU3QUVSUlZIOTVxZ1dzVlhHcGMKLS0tIEc2TlBpWkV4M1NOWmpFMlRNNEl3
            cFZIT3FCcHJhbm9BV0grajlDWWtzRmcKmurTuT6u6GShtUhH7nulvZ+SSk+jE8lq
            VKHVRE3ZMu6YcPSIP7y9nb9K7lvqBLIsBFy7aQVZAvfLKj9JRIHyJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-23T14:14:48Z"
    mac: ENC[AES256_GCM,data:HM8rLTW/sO4IWu2utDNKodB8TWg8OKmJLzmXNbtIlhGSWLUhJL0YjvDuctZVRWwrqal8lKmKn63soF3OwVYtEDVdhzffOttaddPBRDsvKehc+6YegL0wGs5u+ahwjFZu+d3pnA8/c239HrY3+/VqTqw8NSyZqXjHIcLRlnCMXNM=,iv:dIVpGML3BrcDU0KAUHSsSueTEfcROCbF9VRX1qGscuw=,tag:RnTla5QUZZvKYct4ZaG9KQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
