---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: grafana
      version: 19.4.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                GF_SECURITY_ADMIN_USER:
                  secretKeyRef:
                    name: grafana-admin-secret
                    key: user
                GF_SECURITY_ADMIN_PASSWORD:
                  secretKeyRef:
                    name: grafana-admin-secret
                    key: password
    ingress:
      main:
        enabled: true
        ingressClassName: &ingressClass traefik-internal
        annotations:
          kubernetes.io/ingress.class: *ingressClass
          uptime-kuma.autodiscovery.probe.name: "Grafana"
        hosts:
          - host: grafana.clsn.dev
            paths:
              - path: /
                pathType: Prefix
    configmap:
      dashobard-traefik:
        enabled: true
    persistence:
      data:
        enabled: true
        size: 1Gi
        storageClassName: ssd-perf-r3 
          
