---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 5m
  chart:
    spec:
      version: 6.8.0
      chart: ./charts/podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo