---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-external
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 37.1.1
      sourceRef:
        kind: HelmRepository
        name: traefik
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  targetNamespace: traefik-external
  releaseName: traefik-external-traefik
  values:
    namespaceOverride: traefik-external
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.io/loadBalancerIPs: 192.168.95.40
      externalTrafficPolicy: Local
      additionalServices:
        internal:
          type: ClusterIP
          labels:
            traefik-service-label: internal
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        tls:
          enabled: true
      traefik:
        expose:
          default: false
          internal: true
    additionalArguments:
      - "--api.insecure=true"
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: traefik-external
    providers:
      kubernetesCRD:
        ingressClass: traefik-external
        allowExternalNameServices: true
      kubernetesIngress:
        publishedService: 
          enabled: true
        ingressClass: traefik-external
        allowExternalNameServices: true
    metrics:
      prometheus:
        service:
          enabled: true
        disableAPICheck: false
        serviceMonitor:
          enabled: true
          metricRelabelings:
            - sourceLabels: [__name__]
              separator: ;
              regex: ^fluentd_output_status_buffer_(oldest|newest)_.+
              replacement: $1
              action: drop
          relabelings:
            - sourceLabels: [__meta_kubernetes_pod_node_name]
              separator: ;
              regex: ^(.*)$
              targetLabel: nodename
              replacement: $1
              action: replace
          jobLabel: traefik
          interval: 30s
          honorLabels: true
        headerLabels:
          user_id: X-User-Id
          tenant: X-Tenant
        prometheusRule:
          enabled: true
          rules:
            - alert: TraefikExternalDown
              expr: up{job="traefik"} == 0
              for: 5m
              labels:
                context: traefik
                severity: warning
              annotations:
                summary: "Traefik External Down"
                description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"
