---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 35.3.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  targetNamespace: traefik-internal
  values:
    namespaceOverride: traefik-internal
    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: &ip 192.168.95.39
      annotations:
        metallb.io/loadBalancerIPs: *ip
      externalTrafficPolicy: Local
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        tls:
          enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: traefik-internal
    providers:
      kubernetesCRD:
        ingressClass: traefik-internal
        allowExternalNameServices: true
      kubernetesIngress:
        publishedService: 
          enabled: true
        ingressClass: traefik-internal
        allowExternalNameServices: true

