---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-external
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 36.3.0
      sourceRef:
        kind: HelmRepository
        name: traefik
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  targetNamespace: traefik-external
  releaseName: traefik-external-traefik
  values:
    namespaceOverride: traefik-external
    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: &ip 192.168.95.40
      annotations:
        metallb.io/loadBalancerIPs: *ip
      externalTrafficPolicy: Local
      additionalServices:
        internal:
          type: ClusterIP
          labels:
            traefik-service-label: internal
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        tls:
          enabled: true
      traefik:
        expose:
          default: false
          internal: true
    additionalArguments:
      - "--api.insecure=true"
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: traefik-external
    providers:
      kubernetesCRD:
        ingressClass: traefik-external
        allowExternalNameServices: true
      kubernetesIngress:
        publishedService: 
          enabled: true
        ingressClass: traefik-external
        allowExternalNameServices: true

