---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-public
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 35.3.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    api:
      name: api-external
    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: "192.168.95.40"
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.95.40
      externalTrafficPolicy: Local
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        tls:
          enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: traefik-public
    ingressRoute:
      dashboard:
        enabled: false
        services:
          - name: api-external@internal
            kind: TraefikService
    providers:
      kubernetesCRD:
        ingressClass: traefik-public
      kubernetesIngress:
        ingressClass: traefik-public
    tlsStore:
      default: 
        defaultCertificate:
          secretName: clsn-cloud-tls
          namespace: traefik

