---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: 3.12.2
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  install:
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
  releaseName: kube-metrics-server
  targetNamespace: kube-system
  values:
    apiService:
      insecureSkipTLSVerify: false
    tls:
      type: cert-manager
    service:
      type: ClusterIP
      port: 443
      labels:
        kubernetes.io/cluster-service: "true"
        kubernetes.io/name: "Metrics-server"
