---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns-public
  namespace: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 8.9.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 12h
  timeout: 5m
  install:
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  values:
    crd:
      create: true
    sources:
      - crd
      - service
      - ingress
    provider: cloudflare
    cloudflare:
      proxied: true
    extraEnvVarsSecret: external-env-secret
    extraArgs:
      traefik-disable-legacy:
    ingressClassFilters: 
      - traefik-external
    domainFilters:
      - clsn.cloud