---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: external-dns
spec:
  url: https://charts.bitnami.com/bitnami
  interval: 30m0s
  timeout: 3m