---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: external-dns
spec:
  interval: 6h
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts