---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: prometheus
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 5m0s
