---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  timeout: 2m
  chart:
    spec:
      chart: headlamp
      version: 0.31.1
      sourceRef:
        kind: HelmRepository
        name: headlamp
  values:
    # yaml-language-server: $schema=https://raw.githubusercontent.com/kubernetes-sigs/headlamp/refs/heads/main/charts/headlamp/values.schema.json
    ingress:
      ingressClassName: &ingressClass traefik-internal
      enabled: true
      annotations:
        kubernetes.io/ingress.class: *ingressClass
      hosts:
        - host: headlamp.clsn.dev
          paths:
            - path: /
              type: Prefix
    podSecurityContext:
      fsGroup: 1000
    config:
      env:
        - name: HEADLAMP_CONFIG_TRACING_ENABLED
          value: false
      watchPlugins: true
    # Workaround for: https://github.com/kubernetes-sigs/headlamp/issues/1826  
    initContainers:
      - command:
          - /bin/sh
          - "-c"
          - |
            kubectl config set-cluster main --server=https://kubernetes.default.svc --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            kubectl config set-credentials main --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
            kubectl config set-context main --cluster=main --user=main
            kubectl config use-context main
        env:
          - name: KUBERNETES_SERVICE_HOST
            value: 192.168.95.10
          - name: KUBERNETES_SERVICE_PORT
            value: "6443"
          - name: KUBECONFIG
            value: /home/headlamp/.config/Headlamp/kubeconfigs/config
        image: bitnami/kubectl:1.32.0
        name: create-kubeconfig
        securityContext:
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 101
          runAsNonRoot: true
          runAsUser: 100
        volumeMounts:
          - mountPath: /home/headlamp/.config/Headlamp/kubeconfigs
            name: kubeconfig
            readOnly: false

    volumeMounts:
      - mountPath: "/home/headlamp/.config/Headlamp/kubeconfigs/"
        name: kubeconfig
        readOnly: true
    volumes:
      - name: kubeconfig
        emptyDir: {}

    pluginsManager:
      enabled: true
      configContent: |
        plugins:
          - name: cert-manager
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_cert-manager
            version: 0.1.0
          - name: flux
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_flux
            version: 0.2.0
          - name: kompose
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_kompose
            version: 0.1.0-beta-1
