---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  timeout: 2m
  chart:
    spec:
      chart: headlamp
      version: 0.31.1
      sourceRef:
        kind: HelmRepository
        name: headlamp
  values:
   ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik-internal
    hosts:
      - host: headlamp.clsn.dev
  config:
    watchPlugins: true
  persistentVolumeClaim:
    enabled: true
    storageClassName: ssd-perf-r3
    accessModes:
      - ReadWriteOnce
    size: 1Gi
  pluginsManager:
    enabled: true
    configContent: |
      plugins:
        - name: cert-manager
          source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_cert-manager
          version: 0.1.0
        - name: flux
          source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_flux
          version: 0.2.0
        - name: kompose
          source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_kompose
          version:0.1.0-beta-1
