---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: s3-operator
  namespace: minio
spec:
  interval: 5m
  timeout: 2m
  chart:
    spec:
      chart: s3-operator
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: inseefrlab
  values:
    crds:
      # -- Install and upgrade CRDs
      install: true
      # -- Keep CRDs on chart uninstall
      keep: true

    controllerManager:
      replicas: 1
    kubernetes:
      clusterDomain: cluster.local
      overrideExistingSecret: true
      readExistingSecret: true

