---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns-public
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 8.8.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 12h
  timeout: 5m
  targetNamespace: external-dns
  values:
    crd:
      create: true
    sources:
      - crd
      - service
      - ingress
    provider: cloudflare
    cloudflare:
      proxied: true
    extraEnvVarsSecret: external-env-secret
    extraArgs:
      traefik-disable-legacy:
    ingressClassFilters: 
      - traefik-public
    domainFilters:
      - clsn.cloud