---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-public
  namespace: networking
spec:
  chart:
    spec:
      chart: external-dns
      version: 8.8.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: networking
  interval: 15m
  timeout: 5m
  releaseName: external-dns
  install:
    createNamespace: true
  targetNamespace: external-dns
  values:
    crd:
      create: true
    sources:
      - crd
      - service
      - ingress
    provider: cloudflare
    cloudflare:
      secretName: cloudflare-secret
      proxied: true
    extraEnvVarsSecret: external-env-secret
    extraArgs:
      dry-run: true
    ingressClassFilters: 
      - traefik-public
    domainFilters:
      - clsn.cloud