apiVersion: v1
kind: Secret
metadata:
    name: minio-user-console-secret
    namespace: minio
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:e+d3IyxE5GP766+r/9lHzVvBUMBIrc/5jAP8nPn80bs=,iv:JRtlpqwQbF9sINogf3kl4xy7ka1nJWH6qHqyCRoslwQ=,tag:Yy/ecc3hkSrNJcjPD3HfSA==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxanQxQkVRTk9iNW9OZGd6
            dVBjZjZkT1BWYmhvVmJXNzhDd0IxNldvSldvCkpyem1PRHlIVCt2bmxZTS9GUnZa
            RUc4VEo0SmxkWk5EZHB1OE5rTTFwSkkKLS0tIGxyL2dseUQ3SXl2WUg3cTU0SnMx
            Zk00RCs1TkNNRm04a1ZLM3lPbkRXekkKnBEz6ceks1cqMOHPK+HWKsI6SuM4grTP
            i+DlnaQwh/mBzrEqv81Vx83pIkZsX59yir+hLmvQsqWoKdtKXRB0dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-07T19:13:39Z"
    mac: ENC[AES256_GCM,data:UzORT3X/syN/tFRGH12LynU6eZlTlFxZCKcreTw6sICS1eieucT4++JIbLlDVaEFcGS/Zd+DlR6Mqxy64VfN2u1NiS41+WS/GHuXlCpRdZ8nsu+M/QkgpIkoVmPmGMOdB+RRAndTrlMXkQ3wx2B4Em+rcE+UP4n459kYpoi9MBU=,iv:QhGVhnB9WHRj5DpuNUpxmWghS6xX72zRvUunez2UQD4=,tag:QyjAePChLO2Pjp4qqfxMPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: minio-user-notesnook-secret
    namespace: minio
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:E5QYjChEM+06uLsHi72hsfdJg1mGJcEUC+kTrlCEm6o=,iv:RV+PjfGc3NtiwkOl6wi3zX2oBx3NOaiXRBwCC9EUDWo=,tag:wlyRvuchwCUT070ku42qAg==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxanQxQkVRTk9iNW9OZGd6
            dVBjZjZkT1BWYmhvVmJXNzhDd0IxNldvSldvCkpyem1PRHlIVCt2bmxZTS9GUnZa
            RUc4VEo0SmxkWk5EZHB1OE5rTTFwSkkKLS0tIGxyL2dseUQ3SXl2WUg3cTU0SnMx
            Zk00RCs1TkNNRm04a1ZLM3lPbkRXekkKnBEz6ceks1cqMOHPK+HWKsI6SuM4grTP
            i+DlnaQwh/mBzrEqv81Vx83pIkZsX59yir+hLmvQsqWoKdtKXRB0dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-07T19:13:39Z"
    mac: ENC[AES256_GCM,data:UzORT3X/syN/tFRGH12LynU6eZlTlFxZCKcreTw6sICS1eieucT4++JIbLlDVaEFcGS/Zd+DlR6Mqxy64VfN2u1NiS41+WS/GHuXlCpRdZ8nsu+M/QkgpIkoVmPmGMOdB+RRAndTrlMXkQ3wx2B4Em+rcE+UP4n459kYpoi9MBU=,iv:QhGVhnB9WHRj5DpuNUpxmWghS6xX72zRvUunez2UQD4=,tag:QyjAePChLO2Pjp4qqfxMPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
