---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  timeout: 2m
  chart:
    spec:
      chart: minio
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: minio
  install:
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
  values:
    replicas: 3
    drivesPerNode: 2
    persistence:
      storageClass: "ssd-perf-xfs-r1"
      size: 10Gi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik-external
      hosts:
        - s3.clsn.cloud
    consoleIngress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik-internal
      hosts:
        - s3.clsn.dev
    resources:
      requests:
        memory: "2Gi"
      limits:
        memory: "4Gi"
    nodeSelector:
        beta.kubernetes.io/arch: amd64
    policies:
      - name: s3-operator
        statements:
          - effect: Allow
            resources:
              - 'arn:aws:s3:::*'
            actions:
              - 's3:CreateBucket'
              - 's3:GetObject'
              - 's3:ListAllMyBuckets'
              - 's3:ListBucket'
              - 's3:PutObject'
          - effect: Allow
            resources:
              - 'arn:aws:s3:::*'
            actions:
              - 'admin:CreatePolicy'
              - 'admin:GetBucketQuota'
              - 'admin:GetPolicy'
              - 'admin:SetBucketQuota'
              - 'admin:CreateUser'
              - 'admin:ListUsers'
              - 'admin:DeleteUser'
              - 'admin:GetUser'
              - 'admin:AddUserToGroup'
              - 'admin:RemoveUserFromGroup'
              - 'admin:AttachUserOrGroupPolicy'
              - 'admin:ListUserPolicies'
    users:
      - accessKey: console
        existingSecret: minio-user-console-secret
        existingSecretKey: password
        policy: consoleAdmin
      - accessKey: s3-operator
        existingSecret: minio-s3-operator-secret
        existingSecretKey: S3_SECRET_KEY
        policy: s3-operator
