---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  timeout: 2m
  chart:
    spec:
      chart: minio
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: minio
  install:
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
  values:
    replicas: 3
    drivesPerNode: 2
    persistence:
      storageClass: "ssd-perf-xfs-r1"
      size: 10Gi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik-external
      hosts:
        - s3.clsn.cloud
    consoleIngress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik-internal
      hosts:
        - s3.clsn.dev
    resources:
      requests:
        memory: "2Gi"
      limits:
        memory: "4Gi"
    nodeSelector:
        beta.kubernetes.io/arch: amd64
    buckets:
      - name: notesnook
        purge: false
        versioning: true
        policy: download
    policies:
      - name: notesnook
        statements:
          - effect: Allow
            resources:
              - 'arn:aws:s3:::notesnook/*'
            actions:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
              - 's3:ListMultipartUploadParts'
              - 's3:AbortMultipartUpload'
          - effect: Allow
            resources:
              - 'arn:aws:s3:::notesnook'
            actions:
              - 's3:ListBucket'
              - 's3:ListBucketMultipartUploads'
              - 's3:GetBucketLocation'
              - 's3:CreateBucket'
              - 's3:DeleteBucket'
    users:
      - accessKey: console
        existingSecret: minio-user-console-secret
        existingSecretKey: password
        policy: consoleAdmin
      - accessKey: notesnook
        existingSecret: minio-user-notesnook-secret
        existingSecretKey: password
        policy: notesnook