apiVersion: v1
stringData:
    EXTERNAL_DNS_DEFAULT_TARGETS: ENC[AES256_GCM,data:/K6YVXimJ6kVS2LkOZbBPMQWQgehCFH9MIQ+IieWPbRiBYh8DwryBxE1FQ==,iv:QJRZOHMXvpo9utckxHYsc+GpD1+0BGkooEA+lHR7V+o=,tag:+YCmWawLgvYo92md2Go+6A==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:FJjrp8VL6OwJUZxL5feNCJ6RsSS+8ZaknOvh1IJhwl1XPJWGYvjhXQ==,iv:rEgMWFRNGMzcvpo42eDwyJ//36mJQuzafUpnLZmuAL4=,tag:ebLrLQwVvNufvH0O0TFRdQ==,type:str]
kind: Secret
metadata:
    name: external-env-secret
    namespace: external-dns
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWFZEY1BnaHo1R3RUZlcz
            dWVTVUk0cSs3SFhMSzBHUWNnVnhTNkF5akZ3CnNSc2tNSUdtQWNHcEJmNlhobE9G
            VHd0ck5Xb0NENm5IQ3NqTmU3M2J6VEEKLS0tIGZsenQ5V2ViVnZWOHNoVFR2Kzlh
            NjJLNi94UHFzNzVncnV2N0pvVFNZWnMKqXjZyMq1lXGsMeqeBXbK0oAC3E4LfZm9
            RGIS1etCDKOxJeyNflXeThUzJv83cx65zLitC7SIuG6UQ+w7RVY5og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T01:03:45Z"
    mac: ENC[AES256_GCM,data:CetX8RkSIjm0chUhEAuTsmOygvzjT37nqvSpvNQGAHCaTSGzvcBgmoZ1leei+CVkyTOhVtSl5h6/bVsYvBcQ7yxazxiomG1WCYC/Xxrmt4Fn16+4IqAYVegLxBszekD447JwDnoS4WQ+qqYafHYx24sGJSIeD+eZQC+TzRC3cjI=,iv:mpWe6wisihUH0ylo84Ags11J0DKTm8gQiA/VYTd6l/I=,tag:3na9GsGWiTZArDa4JImX/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
