apiVersion: v1
stringData:
    EXTERNAL_DNS_DEFAULT_TARGETS: ENC[AES256_GCM,data:BXAcYme47Hmdefy3iOkBbw/LCcrN7rccbvEeqKLq/+wUjeaOVtfxievBSiFoRn0j49xSiS2gobJzA/dhqfTMKG8qPXqVoRarpWKyiWlaiEqJKzyJ9OavaOgVq3XteqFTgLEdKxpEL1bG//MUqZD6cC/dIwZEpeAtnCR27bFlosge+tMhoQ==,iv:22+pT8Tl6QPsqlyNFEeUp49YqfX67iwJh8PCQRNHuVA=,tag:1z38UJcvMn732Zsp5SAJpg==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:FJjrp8VL6OwJUZxL5feNCJ6RsSS+8ZaknOvh1IJhwl1XPJWGYvjhXQ==,iv:rEgMWFRNGMzcvpo42eDwyJ//36mJQuzafUpnLZmuAL4=,tag:ebLrLQwVvNufvH0O0TFRdQ==,type:str]
kind: Secret
metadata:
    name: external-env-secret
    namespace: external-dns
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWFZEY1BnaHo1R3RUZlcz
            dWVTVUk0cSs3SFhMSzBHUWNnVnhTNkF5akZ3CnNSc2tNSUdtQWNHcEJmNlhobE9G
            VHd0ck5Xb0NENm5IQ3NqTmU3M2J6VEEKLS0tIGZsenQ5V2ViVnZWOHNoVFR2Kzlh
            NjJLNi94UHFzNzVncnV2N0pvVFNZWnMKqXjZyMq1lXGsMeqeBXbK0oAC3E4LfZm9
            RGIS1etCDKOxJeyNflXeThUzJv83cx65zLitC7SIuG6UQ+w7RVY5og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T00:49:10Z"
    mac: ENC[AES256_GCM,data:D32ibnBl6Jxdl2k4y3wx945KmqznaetAqullhrLyd/fdY262W7tg1FAFjmrbaoRQErGVNjVNdCLTesBgBOyJ3iCysuudgvUPkuhW1w1kJ6lJlqMsZLQfouNJL6pHmORodygQsWnXtHTvjB330GfTU05hkAp66s4fplFalUx6EcE=,iv:3su8hWXipA2O/EpPlPl/zi/gS6dZhiKEPjrD+bD3O9I=,tag:RW79uBEN1Y52TYleughHmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
