apiVersion: v1
kind: Secret
metadata:
    name: internal-rfc2136-secret
    namespace: external-dns
stringData:
    rfc2136-secret: ENC[AES256_GCM,data:mxnM++I1mh3OogWhmeli4yo3GEnV5xc2ms0l5h0eeVFMg/5uM2JXEymPDvU=,iv:n9TmZUitLhvpyBawAqS2A6FQd/J4uPJG8nGx2tYoNZU=,tag:6s1EZMl15toD22UYiCrjZA==,type:str]
    rfc2136-keyname: ENC[AES256_GCM,data:gZlE9NZCSog=,iv:o1g5DMGebxp2GXU+F3y4vQ1lM5UykvCUmAhR691BiA4=,tag:w5d2mrc5tnMRgAuPQMPBYQ==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UTNLMm44RmptM2RzM3NF
            Tzk2WjgyVTFaa1RBU1FKTnVMNDBVMXM3VWpNCnZJYU1vdmV4WE0wQ0NGS2ZwUnFs
            Z1REWWVVbkJHbFZnQmtOTGplL2M5MG8KLS0tIEhsaC9hRkdUQ01zOWJxc1RrYXQ0
            NDRLUWFJMHZUNEhkQ1Y0UmFLK0dNdlEK5XVGfifvSi0eEQaRRRlCghggfOUG0RnW
            X87PoLigW/WmpjoZAZIwV8RJvrfXHYBRHWIVpo1S2R62z94r12qUyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T22:30:12Z"
    mac: ENC[AES256_GCM,data:iabmFo5RBesSvMiSQyKhgAbR4ShxjqFELdmLHpeYqkYAHX8VOm4WDxfmIJkKrNpEOv9DjB7OpkP21itGQc8tfvDVocoDxlSZdzJJQ2JTT4GuCtoy0m5V+VEww59YkuTnKQhZvtEV5N1RzahW3ZjcFeZf9uuXj5VhA8SgS8NsIIQ=,iv:l8NgQnM+Zhk0VkZbKRQc2a5Ez2CLjQBFMm9PRlqGTiM=,tag:hXCrFEjzJjtArM7P9d2vMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
