# yaml-language-server: $schema=https://raw.githubusercontent.com/kubernetes-sigs/external-dns/refs/tags/external-dns-helm-chart-1.19.0/charts/external-dns/values.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-internal
  namespace: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
      interval: 12h
  timeout: 5m
  install:
    crds: Skip
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: Skip
    remediation:
      remediateLastFailure: true
      retries: 3
  values:
    sources:
      - crd
      - service
      - ingress
    provider:
      name: rfc2136
    domainFilters:
      - clsn.dev
    txtPrefix: external-dns-
    txtOwnerId: k8s
    policy: sync
    extraArgs:
      ingress-class: traefik-internal
      rfc2136-host: 192.168.1.1
      rfc2136-port: 53530
      rfc2136-zone: clsn.dev
      rfc2136-tsig-secret-alg: hmac-sha256
      rfc2136-tsig-axfr:
    env:
    - name: "EXTERNAL_DNS_RFC2136_TSIG_SECRET"
      valueFrom:
        secretKeyRef:
          name: internal-rfc2136-secret
          key: rfc2136-secret
    - name: "EXTERNAL_DNS_RFC2136_TSIG_KEYNAME"
      valueFrom:
        secretKeyRef:
          name: internal-rfc2136-secret
          key: rfc2136-keyname
