---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-internal
  namespace: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 12h
  timeout: 5m
  install:
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  values:
    crd:
      create: true
    sources:
      - crd
      - service
      - ingress
    ingressClassFilters: 
      - traefik-internal
    domainFilters:
      - clsn.dev
    provider: webhook
    extraArgs:
      webhook-provider-url: http://localhost:8888
      traefik-disable-legacy:
    sidecars:
      - name: adguard-webhook
        image: ghcr.io/muhlba91/external-dns-provider-adguard:v9.2.0
        ports:
          - containerPort: 8888
            name: http
          - containerPort: 8080
            name: healthz
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 5
        env:
          - name: LOG_LEVEL
            value: debug
          - name: ADGUARD_URL
            valueFrom:
              secretKeyRef:
                name: adguard-secret
                key: url
          - name: DRY_RUN
            value: "false" 
