# yaml-language-server: $schema=https://raw.githubusercontent.com/kubernetes-sigs/external-dns/refs/tags/external-dns-helm-chart-1.19.0/charts/external-dns/values.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-internal
  namespace: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
      interval: 12h
  timeout: 5m
  install:
    crds: Skip
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: Skip
    remediation:
      remediateLastFailure: true
      retries: 3
  values:
    sources:
      - crd
      - service
      - ingress
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/muhlba91/external-dns-provider-adguard
          tag: v11.0.0
        service:
          port: 8888
        livenessProbe: 
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe: 
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        env:
          - name: LOG_LEVEL
            value: debug
          - name: ADGUARD_URL
            valueFrom:
              secretKeyRef:
                name: adguard-secret
                key: url
          - name: DRY_RUN
            value: "false"
    domainFilters:
      - clsn.dev
    extraArgs:
      ingress-class: traefik-internal
