---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-public
  namespace: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
      interval: 12h
  timeout: 5m
  install:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  values:
    sources:
      - crd
      - service
      - ingress
    provider:
      name: cloudflare
    domainFilters:
      - clsn.cloud
    extraArgs:
      ingress-class: traefik-external
      traefik-disable-legacy: ""
      cloudflare-proxied: ""
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-env-secret
            key: CF_API_TOKEN
      - name: EXTERNAL_DNS_DEFAULT_TARGETS
        valueFrom:
          secretKeyRef:
            name: external-env-secret
            key: EXTERNAL_DNS_DEFAULT_TARGETS
