---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb-charts
  namespace: metallb
spec:
  url: https://metallb.github.io/metallb
  interval: 30m
  timeout: 3m