apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: node-properties
spec:
  properties:
    - name: Aux/topology/uplink
      valueFrom:
        nodeFieldRef: metadata.labels['topology.kubernetes.io/uplink']