# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.0/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-perf-r3
provisioner: linstor.csi.linbit.com
parameters:
  linstor.csi.linbit.com/disklessOnRemaining: "true"
  linstor.csi.linbit.com/autoPlace: "3"
  linstor.csi.linbit.com/resourceGroup: "ssd-perf-r3"
  linstor.csi.linbit.com/storagePool: "ssd"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.0/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-perf-r1
provisioner: linstor.csi.linbit.com
parameters:
  linstor.csi.linbit.com/disklessOnRemaining: "true"
  linstor.csi.linbit.com/autoPlace: "1"
  linstor.csi.linbit.com/resourceGroup: "ssd-perf-r1"
  linstor.csi.linbit.com/storagePool: "ssd"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.0/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-perf-xfs-r1
provisioner: linstor.csi.linbit.com
parameters:
  linstor.csi.linbit.com/autoPlace: "1"
  linstor.csi.linbit.com/resourceGroup: "ssd-perf-xfs-r1"
  linstor.csi.linbit.com/storagePool: "ssd"
  csi.storage.k8s.io/fstype: xfs
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
