# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.0/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-perf
provisioner: linstor.csi.linbit.com
parameters:
  linstor.csi.linbit.com/allowRemoteVolumeAccess: "true"
  linstor.csi.linbit.com/autoPlace: "2"
  linstor.csi.linbit.com/placementPolicy: "AutoPlace"
  linstor.csi.linbit.com/storagePool: ssd
  linstor.csi.linbit.com/replicasOnSame: "networking/uplink-performance=10G"
  linstor.csi.linbit.com/replicasOnDifferent: "networking/uplink-performance=1G"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.0/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-eco
provisioner: linstor.csi.linbit.com
parameters:
  linstor.csi.linbit.com/allowRemoteVolumeAccess: "true"
  linstor.csi.linbit.com/autoPlace: "3"
  linstor.csi.linbit.com/placementPolicy: "AutoPlace"
  linstor.csi.linbit.com/storagePool: ssd
  linstor.csi.linbit.com/replicasOnSame: "networking/uplink-performance=1G"
  linstor.csi.linbit.com/replicasOnDifferent: "networking/uplink-performance=10G"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---