# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.0/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-perf
provisioner: linstor.csi.linbit.com
parameters:
  linstor.csi.linbit.com/allowRemoteVolumeAccess: "true"
  linstor.csi.linbit.com/placementCount: "2"
  linstor.csi.linbit.com/storagePool: "ssd"
  linstor.csi.linbit.com/disklessOnRemaining: "true"
  linstor.csi.linbit.com/replicasOnSame: "uplink=10G"
  linstor.csi.linbit.com/xReplicasOnDifferent: |
    uplink: 1
  csi.storage.k8s.io/fstype: xfs
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.0/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-eco
provisioner: linstor.csi.linbit.com
parameters:
  linstor.csi.linbit.com/allowRemoteVolumeAccess: "true"
  linstor.csi.linbit.com/placementCount: "2"
  linstor.csi.linbit.com/storagePool: "ssd"
  linstor.csi.linbit.com/disklessOnRemaining: "true"
  linstor.csi.linbit.com/replicasOnSame: "uplink=1G"
  linstor.csi.linbit.com/xReplicasOnDifferent: |
    uplink: 1
  csi.storage.k8s.io/fstype: xfs
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---