---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-internal
  namespace: networking
spec:
  chart:
    spec:
      chart: external-dns
      version: 8.8.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: networking
  interval: 15m
  timeout: 5m
  releaseName: external-dns
  install:
    createNamespace: true
  targetNamespace: external-dns
  values:
    crd:
      create: true
    sources:
      - crd
      - service
      - ingress
    ingressClassFilters: traefik-internal
    domainFilters:
      - clsn.dev
    provider: webhook
    extraArgs:
      webhook-provider-url: http://localhost:8888
    sidecars:
      - name: adguard-webhook
        image: ghcr.io/muhlba91/external-dns-provider-adguard:8.0.1
        ports:
          - containerPort: 8888
            name: http
          - containerPort: 8080
            name: healthz
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 5
        env:
          - name: LOG_LEVEL
            value: debug
          - name: ADGUARD_URL
            valueFrom:
              secretKeyRef:
                name: adguard-secret
                key: url
          # - name: ADGUARD_USER
          #   valueFrom:
          #     secretKeyRef:
          #       name: adguard-configuration
          #       key: user
          # - name: ADGUARD_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: adguard-configuration
          #       key: password
          - name: DRY_RUN
            value: "false" 