---
apiVersion: v1
kind: Service
metadata:
  name: pve
  namespace: internal-services
spec:
  type: ExternalName
  externalName: 192.168.91.10
  ports:
    - name: proxmox
      port: 8006
      targetPort: 8006
      protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pve-ingressroute
  namespace: internal-services
  annotations:
    kubernetes.io/ingress.class: traefik-internal
    uptime-kuma.autodiscovery.probe.name: "Proxmox Cluster"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pve.clsn.dev`)
      kind: Rule
      services:
        - name: pve
          port: proxmox
          scheme: https
          serversTransport: insecure-skip-verify
