apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:Do/BopIXfKS4kgzg2PnjNbCwPmKnxQYl+YH1/FR9tnT7+ijLzWtQDiIalpBs9CMJ/iwUwHVmQtI=,iv:kNyzcP5vN/LbY0UVAvIUhl6bhRaVeGoZGpBHN8vyjNQ=,tag:7FKIraGZYLWviTV3y8+/tg==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQU2l6YlE1WktjaEV5U2xw
            OUhaVDV0OEsyYW81dVNWU2R2VU9wMC9SMGtrCmx2SkRjbmxTT1YyNnZrUHhhdHo4
            bTVrV3haZzdEMUdlQ3lLeGJoejQvMUkKLS0tIFFzREhMRUhOVDZ5VTA0ZFY5MzNs
            N0dmZU8vQTBuSU8vTUdoUVFyK28xMzgK+0XtsQMNPgk1TWrFwaMSbo/dBeDU0VPa
            KX8chhlgaoJ4n+mvFnnbxDy+I0860nCAtklsXLl9BKj03L/uXW5Z7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-31T14:14:48Z"
    mac: ENC[AES256_GCM,data:romjzE0inFf9fLIxwQVNJF68CF+TKwrtqiUUGtbcwZIYllbWmiWwIm13J1efZuI04TSXot19fZDFYeM9A9kmckXatrIudCTa/RY5eZDGWsD75e2sP1w7jAy3tw8M4YxXCWTzDHsYhDyNOkZksxOeGUXfXBxVB7YDBMuBpPCtQAw=,iv:h1D35pmxvBVqRivnub8X6zKctw7q/M/fKJbeLm29/I8=,tag:twciGe3g0fkqmvQ+lcj+Vg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
