apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: clsn-cloud-tls
  namespace: cert-manager
spec:
  secretName: clsn-cloud-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: clsn.cloud
  dnsNames:
    - clsn.cloud
    - '*.clsn.cloud'
