apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: clsn-dev-tls
  namespace: flux-system
spec:
  secretName: clsn-dev-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: clsn.dev
  dnsNames:
    - clsn.dev
    - '*.clsn.dev'
