apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - cloudflare-secret.yaml
  - cloudflare-issuer.yaml
  - clsn-cloud-root-certificate.yaml
  - clsn-dev-root-certificate.yaml
