---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: ca-bundle
spec:
  sources:
    - useDefaultCAs: true
  target:
    configMap:
      key: "ca-pem"
      metadata:
        labels:
          app.kubernetes.io/component: "trust-bundle"
    namespaceSelector:
      matchLabels:
        linkerd.io/inject: "enabled"
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: notesnook-db-ca
spec:
  sources:
    - useDefaultCAs: true
  target:
    configMap:
      key: "ca-pem"
      metadata:
        labels:
          app.kubernetes.io/component: "trust-bundle"
    namespaceSelector:
      matchLabels:
        linkerd.io/inject: "enabled"
