---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: notesnook-kubernetes-secret-store
  namespace: notesnook
spec:
  provider:
    kubernetes:
      remoteNamespace: notesnook
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
