---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: notesnook
resources:
  - namespace.yaml
  - repository.yaml
  - notesnook-mongodb.yaml
  - notesnook-identity-mongodb.yaml
  - notesnook-env-secret.yaml
  - notesnook-s3-secret.yaml
  - mailhog-auth-secret.yaml
  - release.yaml