---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: notesnook
resources:
  - namespace.yaml
  - eso-store.yaml
  - mongodb-service-account.yaml
  - mongodb-ops-manager-config.yaml
  - mongodb-ops-manager-secret.yaml
  - notesnook-mongodb-secret.yaml
  - notesnook-identity-mongodb-secret.yaml
  - notesnook-identity-mongodb-custom-connection-string.yaml
  - notesnook-mongodb.yaml
  - notesnook-env-secret.yaml
  - minio-resources.yaml
  - release.yaml
