---
apiVersion: s3.onyxia.sh/v1alpha1
kind: Bucket
metadata:
  labels:
    app.kubernetes.io/name: bucket
    app.kubernetes.io/instance: bucket-notesnook
    app.kubernetes.io/part-of: s3-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: s3-operator
  name: minio-bucket-notesnook
spec:
  name: notesnook
  quota:
    # 10GB
    default: 10000000000
    # override: 20000000000
---
apiVersion: s3.onyxia.sh/v1alpha1
kind: Policy
metadata:
  labels:
    app.kubernetes.io/name: policy
    app.kubernetes.io/instance: policy-notesnook
    app.kubernetes.io/part-of: s3-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: s3-operator
  name: minio-policy-notesnook
spec:
  name: notesnook
  policyContent: >-
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
              "s3:AbortMultipartUpload",
              "s3:DeleteObject",
              "s3:GetObject",
              "s3:ListMultipartUploadParts",
              "s3:PutObject"
          ],
          "Resource": [
              "arn:aws:s3:::notesnook/*"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
              "s3:CreateBucket",
              "s3:DeleteBucket",
              "s3:GetBucketLocation",
              "s3:ListBucket",
              "s3:ListBucketMultipartUploads"
          ],
          "Resource": [
              "arn:aws:s3:::notesnook"
          ]
        }
      ]
    }
---
apiVersion: s3.onyxia.sh/v1alpha1
kind: S3User
metadata:
  labels:
    app.kubernetes.io/name: user
    app.kubernetes.io/instance: user-notesnook
    app.kubernetes.io/part-of: s3-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: s3-operator
  name: user-notesnook
spec:
  accessKey: s3-notesnook
  policies:
    - notesnook
