---
# According to https://www.mongodb.com/docs/kubernetes/current/tutorial/set-scope-k8s-operator/#std-label-cluster-wide-scope
# Source: mongodb-kubernetes/templates/database-roles.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-kubernetes-database-pods
  namespace: notesnook
