apiVersion: v1
kind: Secret
metadata:
    name: notesnook-mongodb-identity-connection-string
    namespace: notesnook
type: Opaque
stringData:
    connectionString.standard: ENC[AES256_GCM,data:Vr1bNT7UyK1a5FrLGW+6yVl4aV8GG893xYbbBHShkN9Mk0Rhpk7fNezP11fEQk1ZbaDDXJoBmeFfnbnYnn7btwyn3k9vrBTN3v8Dtedw/+jRS7kTcA9RdJKb2Y0bryVGM1up5RyhnPMjcEWxVI7QraBOvEMHVliSxa26HYhW+WjzGPhsb+fXzLr2pSc4ewpLnqWCjZbHP+9lvIVtHfqZkLqqwPMdLJAobE2ZY4zinC8u/N7jV9Bel7lJ0g3VvYQtremM1A7DR3iOgp5MPqSH8cqWlj8QHNg1yx4Ij3dphGsoWHBxMm+8i6kShPkfzQEDyaQWYAHc3Pq/DUlZY+DsOlQkgUG0LHkbnS8nYpPX7eVSmVDk1PKIsmnPBjazQv+G3kgN4VGVztDNXIZ6snKDNThmWRQ7n0GSZkivfxhW3GmDTmbbcEA5/cpgj0Ix4HiIN6FGPWrI2Fl0ipTGqOxld7empfdd6WqdBFsIUhjesKqtYJKLNJL88DyKYTARNwGoDkYXn5Y+hg4rvp1TZsa+c7y9,iv:pCNm/GG8USWzXAw757EtfFTsXWoIbqoDpMPO9tl+ZMo=,tag:q6/PEDYMn8hkXxACXnJgiw==,type:str]
    connectionString.standardSrv: ENC[AES256_GCM,data:DuthS6AA6SEHw8hbGyhlgxZc6azGr/oZaC2zfkWl/DhJfQQd04xSI1BogkXgzp4W5x5Lb+YQ2ZsFKshB9HpEx0/KirdAmCkj/fUjqQJjH43CZxrwekQuMBxX4MCpvFkkGfYoc8UW7iswz71aDK0VrsLIaOezNNJ89Vcrb8Q/gmY/FfoCQxphz3Wkv7bZvkkUNkuDe1TQPObAC2SRLweD/8fKUUUZi74M+l5hbRQvaoQ1tdHygSeOryk8xyt36r8pdCmMhLQg40Z04qbT+nApoqZO6XwkzOv8xaEYV7K5TwprZxE7uwuqo2ppsdiWkQ8lZIib1G3Kpa+ArDh2bQ==,iv:dygD6nT3kHXFxzhtqod+DmG276DsifPsijrj23j/xD4=,tag:HZvsJPwbGOm7rTUr1ubp3A==,type:str]
    password: ENC[AES256_GCM,data:c4hfNfCLQ4TSePe9h9SaeqKKquNP0uFR95m3DFlWKls=,iv:uaue7NiULrfwng5bDNlcigjajLEjH7tfxjLJDIhuV60=,tag:R6ymfOROt9lcpxp2lRyL7g==,type:str]
    username: ENC[AES256_GCM,data:21omrOBHydpN,iv:MwwuQw+o1bv3HfU8XYkZrSbu00vhHXG7EvQE48UXPJ4=,tag:IBpCkFuAf4V3J5SW8w+8fQ==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNi9qZUEwY3JSaUFEK1Zm
            eGhpSDcrWHNWUU8xMlF6NDhPSTUwSkhuVTBrCm9uWjMyTmpxK1F3UEEwMFlPaThW
            dkJqYk9QS0R4RE5PU1lodGJkNGVkcGcKLS0tIHNkeGsrdDVXL1ArZG5JdkJVVDZZ
            QW9ORFpSS0NaQzFLRU0rNzMvYndDSm8K+qO8QW57z2q814efdfEwfZ9/zxN1BpKx
            vJfWkSaLd6XrS5Op5PYKfVxcD3HgSWXcBPSGbFkEruLgtIcDpTNZDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-10T11:33:50Z"
    mac: ENC[AES256_GCM,data:tYDXYj60diyl+Uu1rT8VzVcN/q9aB+reBlT5vAd4RG1N58UKzFVlnBpiUjAtSzvgXjlq+aZYEXc5EqZXY6OkqACpniVWlrsrrwNrNpay7rjKIMbuIfU23TzbWorjb4MIPScyW2otX+LpVWOEhinXgVYPvXfJjnix+wOYC10dc2k=,iv:Teqvx79iWZl5BMpVGn+WHlZWVvVcO9OeSW6aRFhufws=,tag:g46ImJ6KiUO4gCrMdpwPSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
