apiVersion: v1
kind: Secret
metadata:
    name: notesnook-identity-mongodb-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:jW3oTEYjA6W88SwRV33pjQCsXbYr8HSPr+8qFHghZd4=,iv:0jk2xp1nf6ynXt2wpcT3ZWUAwG8BD3TTRymKtNMF0Qk=,tag:U+Ly5nfkNy3W9KYUGHTQ5Q==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQY2dDOWRMcmVQUFdwOEFG
            cDU2SnJRQVZGQm8wVTA0SkR2MWNuNlludjFvCnFaSmlFVW5QUkhseGZNbnRUSXlD
            dTgwekhHSlJWVDM3ZFR5UVdubzI3YWcKLS0tIFNZNm5sUEI3WlNnMTZzNDEzQUhH
            cUQ1a1JrMXE1c0xGbW11dnZLd0hlNEEKoJAuhIMYhdwy/nEzTzFD8ZM8UHHkaawX
            WTsNx0vVcFkBDWm8wmD9rrDge2ZgNilMitVmcYIIcDkdFNNhQ7xsgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-11T11:30:17Z"
    mac: ENC[AES256_GCM,data:grIBliH3GI+DPBlzwQtMfEWZX8imX28cwPBr4f2gaLNiy0PDvW+FqK1Hz4hn5VnDfN0kZqln5OWTcFm1xoM39M7dypSngSABdideBO9YJakQJymXAbSh44hqASe28ikjgttVCAQW9tama4cU9hLwh0MIewxpLixfjrsaCSs8J78=,iv:it92OyOLNkJOeFMdPAG8zzezqONGOfHYoWujoTVGPBs=,tag:01sQpeqwmczqlvpOm7au6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
