apiVersion: v1
kind: Secret
metadata:
    name: notesnook-identity-mongodb-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:65kiD5FKJ78UUnuT7sMYksvvnqyl392WRXWDitWf9dA=,iv:Bdp6LLR+t0IE9k49vDeG1xE9Gi5tQnVCylfg9NZlHx8=,tag:zdWhCiWWsmlxh7LfBc35xw==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQY2dDOWRMcmVQUFdwOEFG
            cDU2SnJRQVZGQm8wVTA0SkR2MWNuNlludjFvCnFaSmlFVW5QUkhseGZNbnRUSXlD
            dTgwekhHSlJWVDM3ZFR5UVdubzI3YWcKLS0tIFNZNm5sUEI3WlNnMTZzNDEzQUhH
            cUQ1a1JrMXE1c0xGbW11dnZLd0hlNEEKoJAuhIMYhdwy/nEzTzFD8ZM8UHHkaawX
            WTsNx0vVcFkBDWm8wmD9rrDge2ZgNilMitVmcYIIcDkdFNNhQ7xsgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-10T11:59:07Z"
    mac: ENC[AES256_GCM,data:nZbaZjfBYSXcgmIdL6DN5+52AkvjPqQYaJkv1NziCBJ1TY7GZSm1t1j/O4lOiuJXcUYZSTH5HBe+EOFSXUr6XRokode8KxP/M1bUt3/QH0gplz7NIsN7tJtDi/vhHGqVytyIGZxMxiB7R+Zr42nzeMHy3GyXw11uBnopN5bPOnk=,iv:O4eK+1iDWWP9/WXqrJ5mUyiCNe31KUfLQ5y1T9eOjwU=,tag:3mkkCkM3sTUNVYtUW8h4Rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
