---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: notesnook-identity
  namespace: notesnook
spec:
  version: 8.0.0
  members: 3
---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: notesnook-identity-mongodb-user
spec:
  username: "notesnook-identity"
  db: "notesnook-identity"
  connectionStringSecretName: notesnook-identity-mongodb-connection-string
