apiVersion: v1
kind: Secret
metadata:
    name: notesnook-mongodb-identity-connection-string
    namespace: notesnook
type: Opaque
stringData:
    connectionString.standard: ENC[AES256_GCM,data:Af79HWaj8KhT40KC3ads7Mmx46tOUSUl3ZcWLB1KiXRmcojGCL26gnUiPpRBiigTN6KW6JK714E6ZzBDVFVWD4PYupgPlOBOp2X6n0pg6ujOK44dTsH6QnXXRo8PiCpX/do8StlsFnO/pugxFKy83C5MkosswWyVCpy3kkff3oi6N1L7trlCABcp5y2A5gv0g0SPx8kBqott02WU4L0kH8TLIcWEgLJIK0w74umc7NtSNOtl3WjbuZSs3RCNes+MpyYA5XkVQtb0839eV5R9+cUzeHxb3G8+4xJ7MVyRTaQ44ylE/QxXwF3NXMa5GdFqstlE2OGuVFr9GLtPyMdjOgwsA+IYVguaPsMZcOjo3esygu6+5Z7Atqq6uV54w7aFSwv/vyCMKdyyCmbAzibmE7UAf9YYfgFRP0AUablXnQ+cjZz6Wg+2o2lp+I6UR66h52QIcUc3L9W/99sMofGxWaZWiSF/sdSVtKGNSRtn0R5xqX4pJRelFBQ8vfAhfg==,iv:YnZ0P0GccHGlu4pLelieI6uuayQVQlqrmDWgCUpgwEQ=,tag:lp/QFmZXC63PH+X6rF4Vpg==,type:str]
    connectionString.standardSrv: ENC[AES256_GCM,data:k8DtyjKkbLN5NoJcS946hp8l4l35Vc7bOn27Dz0F6SwOFLgzBCc1PJavOuNeKNOcn0y9SAbpCDg/5pFyFPiHvZfvquMTUN0HIadOsWJu8vHYDf6ZCPtGgYMK5xQ6jwzA+OTrUt60GNLY/PLfKQLcwsmX21xF4BUM8bDttgjL5h/kpwBoiMtLfljk/nUvhIDsyymSHeZDxa1Sz2wEk+uODb2eegERVDDlLunH3ICoA/JReTAGxNt53ISMqk7FCldMIqPb0UZ4240wbBZjtNoZkL4uz0ou3ICfyWx8HepYQQaZcD/SqhOwqd0=,iv:y22G2sbAoqnxR8r3HDkyaLztaYAT+INX4y6gEG721eY=,tag:GIPJx3a6j3nBGej7icaeyQ==,type:str]
    password: ENC[AES256_GCM,data:c4hfNfCLQ4TSePe9h9SaeqKKquNP0uFR95m3DFlWKls=,iv:uaue7NiULrfwng5bDNlcigjajLEjH7tfxjLJDIhuV60=,tag:R6ymfOROt9lcpxp2lRyL7g==,type:str]
    username: ENC[AES256_GCM,data:21omrOBHydpN,iv:MwwuQw+o1bv3HfU8XYkZrSbu00vhHXG7EvQE48UXPJ4=,tag:IBpCkFuAf4V3J5SW8w+8fQ==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNi9qZUEwY3JSaUFEK1Zm
            eGhpSDcrWHNWUU8xMlF6NDhPSTUwSkhuVTBrCm9uWjMyTmpxK1F3UEEwMFlPaThW
            dkJqYk9QS0R4RE5PU1lodGJkNGVkcGcKLS0tIHNkeGsrdDVXL1ArZG5JdkJVVDZZ
            QW9ORFpSS0NaQzFLRU0rNzMvYndDSm8K+qO8QW57z2q814efdfEwfZ9/zxN1BpKx
            vJfWkSaLd6XrS5Op5PYKfVxcD3HgSWXcBPSGbFkEruLgtIcDpTNZDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-10T11:40:04Z"
    mac: ENC[AES256_GCM,data:79BHXFgyByw5E7BIi20GOqLcMAYYFxAZt+nbaBDda3S54eXWOct4FsvtuWOU29jypxqFmOu5QaDEBT/JXtlYom7AIbd6Lm02gKjHHQ+0CGAGQvRXyNCXHCSpIOg29+JtgxPSPHM9xJw6ZtSYEmVK8JdU847k3YmKD6y80ztjsgk=,iv:F29Rp446hTzUHxBBsnJNhMy7sr7DlPwYHzYsvfW07tk=,tag:6l/1rp5F084fnRf17z+EZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
