---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: notesnook-db
  namespace: notesnook
spec:
  type: ReplicaSet
  version: 8.0.7
  members: 3
  opsManager:
    configMapRef:
      name: mongodb-ops-manager-config
  credentials: mongodb-ops-manager-secret
  persistent: true
  podSpec:
    persistence:
      single:
        storage: 10Gi
        storageClass: ssd-perf-xfs-r1
---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: notesnook-mongodb-user
spec:
  username: "notesnook"
  passwordSecretKeyRef:
    name: notesnook-mongodb-secret
    key: password
  db: "notesnook"
  mongodbResourceRef:
    name: notesnook-db
  connectionStringSecretName: notesnook-mongodb-connection-string
