---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: notesnook-identity
  namespace: notesnook
spec:
  type: ReplicaSet
  version: 8.0.7
  members: 3
  opsManager:
    configMapRef:
      name: mongodb-ops-manager-config
  credentials: mongodb-ops-manager-secret
  persistent: true
  configSrvPodSpec:
    persistence:
      single:
        storage: 1Gi
        storageClass: ssd-perf-xfs-r1
---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: notesnook-identity-mongodb-user
spec:
  username: "notesnook-identity"
  db: "notesnook-identity"
  connectionStringSecretName: notesnook-identity-mongodb-connection-string
