apiVersion: v1
kind: Secret
metadata:
    name: notesnook-mongodb-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:emn541OE6wfKW5UOjCB1fon4iB+9T7i5IUfgJ482Y54=,iv:nKfqKvFjoFEubYQRklLXmBk9PC/f+0elpnPhdeNcr4g=,tag:0qBWXwGOJm5eEtsvJsYiYw==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQY2dDOWRMcmVQUFdwOEFG
            cDU2SnJRQVZGQm8wVTA0SkR2MWNuNlludjFvCnFaSmlFVW5QUkhseGZNbnRUSXlD
            dTgwekhHSlJWVDM3ZFR5UVdubzI3YWcKLS0tIFNZNm5sUEI3WlNnMTZzNDEzQUhH
            cUQ1a1JrMXE1c0xGbW11dnZLd0hlNEEKoJAuhIMYhdwy/nEzTzFD8ZM8UHHkaawX
            WTsNx0vVcFkBDWm8wmD9rrDge2ZgNilMitVmcYIIcDkdFNNhQ7xsgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-09T20:05:47Z"
    mac: ENC[AES256_GCM,data:SEnBcJneKXrs9PmnaKKwm0QS0OYYP6C3JL7rZ3mc1UMetlkYpHlPOlEJ0zdXWkCSN0jtNtzNyWs7pWS2Omaa+kKH3K1LViFNJgmFnnhcX3ePKio9MhmefjeAKoiJZvG2i8SuxADa1yg39XVnQzqoBwPGrjCsguuGQa51R6XJDrM=,iv:7xB6dNb5wfkrkvR3HNFuV4uTu0ZdN9lOePokzwcJkb4=,tag:85z1tcgziQ7cDxz255EsOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
