apiVersion: v1
kind: Secret
metadata:
    name: notesnook-identity-mongodb-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:5A40Dh82Y3WPt43FMzVYPezqxBIhe5Pa7MJjgSfWBP0=,iv:COhS+JnCQCNzJ/iPbLd16m/ow/e0bKG8UtGh5ibOOqI=,tag:jX9SEVFpMKS+VfczPeXVxA==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQY2dDOWRMcmVQUFdwOEFG
            cDU2SnJRQVZGQm8wVTA0SkR2MWNuNlludjFvCnFaSmlFVW5QUkhseGZNbnRUSXlD
            dTgwekhHSlJWVDM3ZFR5UVdubzI3YWcKLS0tIFNZNm5sUEI3WlNnMTZzNDEzQUhH
            cUQ1a1JrMXE1c0xGbW11dnZLd0hlNEEKoJAuhIMYhdwy/nEzTzFD8ZM8UHHkaawX
            WTsNx0vVcFkBDWm8wmD9rrDge2ZgNilMitVmcYIIcDkdFNNhQ7xsgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-11T11:47:46Z"
    mac: ENC[AES256_GCM,data:BarLqPBaFc7obx7PMeH9LGrSQxBDnyW1JYMnO9iFnEcqzlQx731if2Yy5JiKih+WjFUl5choOGw2PznuMrtER0Tndgp0y4aM/sFn9ziDGFPKD3moEZ88J+YKc9advD9ZuSvnzrkUuFTEvzzxlLieaVXBQxC3n/3zBIuXOQXgnt4=,iv:/G05+MeHxoMNOQHJNCyfqKT2cvUYJGgOTYJyqBuBCHU=,tag:FNfXPuyP1Bt9r327WdXn/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
