apiVersion: v1
kind: Secret
metadata:
    name: notesnook-identity-mongodb-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:zGv0wnYcEIq9ACeiYE8IJpJyUI76bPZRs5yVjbHwqdE=,iv:GXXlv+ndCOXmpQ1a2RwMPvPtCkDWh4YopOUe1KJBwCM=,tag:Zno6dzuRnNg1jW+WMIUebg==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQY2dDOWRMcmVQUFdwOEFG
            cDU2SnJRQVZGQm8wVTA0SkR2MWNuNlludjFvCnFaSmlFVW5QUkhseGZNbnRUSXlD
            dTgwekhHSlJWVDM3ZFR5UVdubzI3YWcKLS0tIFNZNm5sUEI3WlNnMTZzNDEzQUhH
            cUQ1a1JrMXE1c0xGbW11dnZLd0hlNEEKoJAuhIMYhdwy/nEzTzFD8ZM8UHHkaawX
            WTsNx0vVcFkBDWm8wmD9rrDge2ZgNilMitVmcYIIcDkdFNNhQ7xsgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-11T11:43:01Z"
    mac: ENC[AES256_GCM,data:uXyjZ4AK+ttMCiRHEiwuPhoC8D20IjXrntm+SFFTfyhRdu/jHEb0IohflXmKB6FRFoqxZghKM3oDw1Dlo42L6s8oKUaYp0bIaT3EKqX/FQ0TvN74CMZrWguYC7bzJSmaB8Man32R/BNN92P/FC4f63cqAkDjZY2mtF+21q8rWdo=,iv:vLZayL6LSH6ORz+DDWlL9fCg7C+Fw20HrJrxvcol7I0=,tag:NA0Me9OeyM6niwCWV/3ZHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
