apiVersion: v1
kind: Secret
metadata:
    name: notesnook-mongodb-identity-connection-string
    namespace: notesnook
type: Opaque
stringData:
    connectionString.standard: ENC[AES256_GCM,data:U4B8MFHdGHtzX2N6mELQDOx5PA6ij3Pn3xpDjH6sHeEaqB+fbFrYA7Rw/9ncigtYsOBa22eT+8Y8h9l+/t1T82y/n1wi6HzWDJ9zbiYITXpj1AvKIOJ5gMA1nBdxAAbFr9b77T1e6GwxSkAtMIhkm4/li77QWDU1yWXU1x8ZpbsDKON84yOa22eZMO81VxiSjb2fzDFvPTWCsxLQHKHgwNce67TjfJfwt7VGJJvm3QVgfLEt5iWJwR+DUeaV1JlwewqClxMrmJqxESd3CNeiBsoem5cL57pDmAEjV+8jR43nRB4BweQ5+V/J4LYfGZ3gIFGa15ksu//9B6er5vnORCY5+xcHS/McCAsCHEnXtgGkGd34pFeFQwTGuM6GEuLgWmXzX+hC,iv:3iK7Q4b2ByOnF9Mprl6D7myEdTur4ceebvLwVlQOhTo=,tag:EeFgrkm/T3BdsrAz85yPLA==,type:str]
    connectionString.standardSrv: ENC[AES256_GCM,data:qTXh8dyauTwM8mjIgANaeT0lbn8wm+cdgiPeRy9WgxSqhCB2MDDiqEIrF9o9sN/CHLLJWwEkJkAY1GyxTwpIoQOMa/qgxvmvgMzhqTa6n/w+thIlAw2+BJJ6hV2uEZpxUKsuzvPCk+Pol0LUoKbjUHi5Twdg8hMHtNH9gRmYIRm9ryCvxVfYbd6vY4nfCCcRrw==,iv:h9ehdszICZX+F2WNO5wSA4F/Wy7LMteqRzLbiQtBAus=,tag:/Sz3Ivz7ZL6uVvWsgV1baw==,type:str]
    password: ENC[AES256_GCM,data:c4hfNfCLQ4TSePe9h9SaeqKKquNP0uFR95m3DFlWKls=,iv:uaue7NiULrfwng5bDNlcigjajLEjH7tfxjLJDIhuV60=,tag:R6ymfOROt9lcpxp2lRyL7g==,type:str]
    username: ENC[AES256_GCM,data:21omrOBHydpN,iv:MwwuQw+o1bv3HfU8XYkZrSbu00vhHXG7EvQE48UXPJ4=,tag:IBpCkFuAf4V3J5SW8w+8fQ==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNi9qZUEwY3JSaUFEK1Zm
            eGhpSDcrWHNWUU8xMlF6NDhPSTUwSkhuVTBrCm9uWjMyTmpxK1F3UEEwMFlPaThW
            dkJqYk9QS0R4RE5PU1lodGJkNGVkcGcKLS0tIHNkeGsrdDVXL1ArZG5JdkJVVDZZ
            QW9ORFpSS0NaQzFLRU0rNzMvYndDSm8K+qO8QW57z2q814efdfEwfZ9/zxN1BpKx
            vJfWkSaLd6XrS5Op5PYKfVxcD3HgSWXcBPSGbFkEruLgtIcDpTNZDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-09T22:45:23Z"
    mac: ENC[AES256_GCM,data:VGYl+pDOlzTjLb9/CSQabVsBpaqUpY2R3cBAQNF2l4VnFqXlIsznQEuJXujT4nQ5YkyJ0ipllXDEcVip0EHI4LgjuJCOvLreTa6tnFRVA/K8BMFfByiBG3BFRnFUzUWNM7eIArjN25O+/HUMqHhwYFJv2Eq89q7atbEj0JEXQK4=,iv:QOc/gnkeCvQocjmbStmiXmxSY6MYaHK/Hj3MC25OjWw=,tag:jmDHNeeGh6F+NcPZrUGj4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
