---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: notesnook-identity-db
  namespace: notesnook
spec:
  type: ReplicaSet
  version: 8.0.7
  members: 3
  opsManager:
    configMapRef:
      name: mongodb-ops-manager-config
  credentials: mongodb-ops-manager-secret
  persistent: true
  podSpec:
    persistence:
      single:
        storage: 1Gi
        storageClass: ssd-perf-xfs-r1
    # multiarch does not seem to be supported by mongodb-kubernetes yet
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: notesnook-identity-mongodb-user
spec:
  username: "notesnook-identity"
  passwordSecretKeyRef:
    name: notesnook-identity-mongodb-secret
    key: password
  db: "notesnook-identity"
  mongodbResourceRef:
    name: notesnook-identity-db
  connectionStringSecretName: notesnook-identity-mongodb-connection-string
