---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: notesnook
  namespace: notesnook
spec:
  interval: 5m
  timeout: 2m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        defaultContainerOptionsStrategy: merge
        defaultContainerOptions:
          env:
            NOTESNOOK_SERVER_PORT: &notesnookServerPort 5264
            NOTESNOOK_SERVER_HOST: &notesnookServerHost notesnook
            NOTESNOOK_API: &notesnookApi notesnook:5264
            IDENTITY_SERVER_PORT: &identityServerPort 8264
            IDENTITY_SERVER_HOST: *notesnookServerHost
            SSE_SERVER_PORT: &sseServerPort 7264
            SSE_SERVER_HOST: *notesnookServerHost
            MONOGRAPH_PORT: &monographPort 3000
            MONOGRAPH_HOST: *notesnookServerHost
            SELF_HOSTED: 1
            NOTESNOOK_APP_PUBLIC_URL: &notesnookAppUrl https://sync.notes.clsn.dev
            NOTESNOOK_APP_PUBLIC_HOST: &notesnookAppPublicHost sync.notes.clsn.dev
            MONOGRAPH_PUBLIC_URL: &monographPublicUrl https://mngrph.clsn.cloud
            MONOGRAPH_PUBLIC_HOST: &monographPublicHost mngrph.clsn.cloud
            ATTACHMENTS_SERVER_PUBLIC_URL: &attachmentsServerUrl https://s3.clsn.cloud
            SSE_SERVER_PUBLIC_URL: &sseServerUrl https://sse.notes.clsn.dev
            SSE_SERVER_PUBLIC_HOST: &sseServerPublicHost sse.notes.clsn.dev
            AUTH_SERVER_PUBLIC_URL: &authServerUrl https://auth.notes.clsn.dev
            AUTH_SERVER_PUBLIC_HOST: &authServerPublicHost auth.notes.clsn.dev
            IDENTITY_SERVER_URL: *authServerUrl
            NOTESNOOK_APP_HOST: *notesnookAppUrl
            DISABLE_SIGNUPS: false
          envFrom:
            - secretRef:
                name: notesnook-env-secret
        containers:
          main:
            image:
              repository: docker.io/streetwriters/notesnook-sync
              # renovate datasource=docker depName=docker.io/streetwriters/notesnook-sync
              tag: v1.0-beta.1
            env:
              MONGODB_CONNECTION_STRING:
                valueFrom:
                  secretKeyRef:
                    name: notesnook-mongodb-custom-connection-string
                    key: "connectionString.standard"
              MONGODB_DATABASE_NAME: notesnook
              S3_INTERNAL_SERVICE_URL: *attachmentsServerUrl
              S3_INTERNAL_BUCKET_NAME: notesnook
              S3_BUCKET_NAME: notesnook
              S3_ACCESS_KEY_ID:
                valueFrom:
                  secretKeyRef:
                    name: s3-user-notesnook
                    key: accessKey
              S3_ACCESS_KEY:
                valueFrom:
                  secretKeyRef:
                    name: s3-user-notesnook
                    key: secretKey
              S3_SERVICE_URL: *attachmentsServerUrl
          identity:
            image:
              repository: docker.io/streetwriters/identity
              # renovate datasource=docker depName=docker.io/streetwriters/identity
              tag: v1.0-beta.1
            env:
              MONGODB_CONNECTION_STRING:
                valueFrom:
                  secretKeyRef:
                    name: notesnook-identity-mongodb-custom-connection-string
                    key: "connectionString.standard"
              MONGODB_DATABASE_NAME: identity
          sse:
            image:
              repository: docker.io/streetwriters/sse
              # renovate datasource=docker depName=docker.io/streetwriters/sse
              tag: v1.0-beta.1
          monograph:
            image:
              repository: docker.io/streetwriters/monograph
              # renovate datasource=docker depName=docker.io/streetwriters/monograph
              tag: 1.2.4
            env:
              PUBLIC_URL: *monographPublicUrl
              API_HOST: *notesnookApi

    service:
      main:
        forceRename: notesnook
        enabled: true
        ports:
          sync:
            port: *notesnookServerPort
          sse:
            port: *sseServerPort
          auth:
            port: *identityServerPort  
          http:
            port: *monographPort

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik-internal
          cert-manager.io/cluster-issuer: letsencrypt-prod
          uptime-kuma.autodiscovery.probe.name: "Notesnook Sync"
          uptime-kuma.autodiscovery.probe.path: "/version"
        hosts:
          - host: *notesnookAppPublicHost
            paths:
              - path: /
                service:
                  identifier: main
                  port: sync
        tls:
          - hosts:
            - *notesnookAppPublicHost
            secretName: notesnook-sync-tls
      monograph:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik-external
          cert-manager.io/cluster-issuer: letsencrypt-prod
          uptime-kuma.autodiscovery.probe.name: "Notesnook Monograph"
        hosts:
          - host: *monographPublicHost
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
            - *monographPublicHost
            secretName: monograph-tls
      identity:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik-internal
          cert-manager.io/cluster-issuer: letsencrypt-prod
          uptime-kuma.autodiscovery.probe.name: "Notesnook Identity"
          uptime-kuma.autodiscovery.probe.path: "/version"
        hosts:
          - host: *authServerPublicHost
            paths:
              - path: /
                service:
                  identifier: main
                  port: auth
        tls:
          - hosts:
            - *authServerPublicHost
            secretName: notesnook-auth-tls
      sse:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik-internal
          cert-manager.io/cluster-issuer: letsencrypt-prod
          uptime-kuma.autodiscovery.probe.name: "Notesnook SSE"
          uptime-kuma.autodiscovery.probe.path: "/version"
        hosts:
          - host: *sseServerPublicHost
            paths:
              - path: /
                service:
                  identifier: main
                  port: sse
        tls:
          - hosts:
            - *sseServerPublicHost
            secretName: notesnook-sse-tls
