---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: notesnook
  namespace: notesnook
spec:
  interval: 5m
  timeout: 2m
  chart:
    spec:
      chart: notesnook
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: notesnook
  values:
    env:
      NOTESNOOK_APP_PUBLIC_URL: https://notes.clsn.dev
      MONOGRAPH_PUBLIC_URL: https://mngrph.clsn.cloud
      ATTACHMENTS_SERVER_PUBLIC_URL: &attachmentsServerUrl https://s3.clsn.cloud
      AUTH_SERVER_PUBLIC_URL: &authServerUrl https://auth.notes.clsn.dev
      DISABLE_SIGNUPS: false
    controllers:
      main:
        defaultContainerOptions:
          envFrom:
            - secretRef:
                name: notesnook-env-secret
        containers:
          main:
            env:
              - name: MONGODB_CONNECTION_STRING
                valueFrom:
                  secretKeyRef:
                    name: notesnook-mongodb-connection-string
                    key: "connectionString.standard"
              - name: MONGODB_DATABASE_NAME
                value: notesnook
              - name: S3_INTERNAL_SERVICE_URL
                value: "http://minio.minio.svc.cluster.local:9000"
              - name: S3_INTERNAL_BUCKET_NAME
                valueFrom:
                  secretKeyRef:
                    name: notesnook-s3-secret
                    key: bucket
              - name: S3_BUCKET_NAME
                valueFrom:
                  secretKeyRef:
                    name: notesnook-s3-secret
                    key: bucket
              - name: S3_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: notesnook-s3-secret
                    key: username
              - name: S3_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: notesnook-s3-secret
                    key: password
              - name: S3_SERVICE_URL
                value: *attachmentsServerUrl
          identity:
            env:
              - name: MONGODB_CONNECTION_STRING
                valueFrom:
                  secretKeyRef:
                    name: notesnook-identity-mongodb-connection-string
                    key: "connectionString.standard"
              - name: MONGODB_DATABASE_NAME
                value: notesnook-identity
    ingress:
      main:
        enabled: true
        className: traefik-internal
      monograph:
        enabled: true
        className: traefik-external
      identity:
        enabled: true
        className: traefik-internal

    mailhog:
      enabled: false
