apiVersion: v1
kind: Secret
metadata:
    name: protonmail-bridge-webui-auth-secret
    namespace: protonmail
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:GlYCEOldZtc=,iv:bIddpn/zmZBYDPQJpX7JgFc9KaxUK9x1XS8KMByOX/M=,tag:5l2KQ0xKIXXa7SHUPAPThA==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSGlWc0JjeFplSWVPWERi
            UjRndzRzY3Y5S3FvUy9ZdnNsRVgwZTBMNGhnCm85NDJHYlJ3TEVEY0lhNmpZRUxw
            Nzg3UEhiOFMxQktOMXlOSnFqeE1sME0KLS0tIGpWNHVrOHJsVDZWWmpWY2dKcU1B
            RzJxVlRybzZHMzhxY0FSMXFUbFZmeTgKjsAsWH9tfxxKCvUNYp6Ss0e3zmmVrVt5
            IR9ucd6r/4jBOkxd9B4vCHd1kUq9gcvJIc6+EID5ipGFkZFRTPWGcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T23:52:04Z"
    mac: ENC[AES256_GCM,data:UQ6TTT1w5OIhMxXiIUPFqvtRuCppsFhiLzjQLfm6ceMNkCz8vKmgf4JgIkzZgtlhvmHUhKsZKJl5S0gyVB2thYm0km+yd5cFMTiqS3SAX9SYlnyTAj7b6lHJSBkxNVkJs/RKp0gvH/LNsTne28PLsGqZyq3HiIk9iE+H3LHBN2E=,iv:o5TSVV0jGKI0B4sWILuGzD76pZtV+2GZyrNkAurP0c8=,tag:23r7ilLM0RMVIL/P6LEzpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
