---
apiVersion: v1
kind: Service
metadata:
  name: adguard-01
  namespace: internal-services
spec:
  type: ExternalName
  externalName: 192.168.95.11
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-01-ingressroute
  namespace: internal-services
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`adguard-01.clsn.dev`)
      kind: Rule
      services:
        - name: adguard-01
          port: http
          scheme: http
          serversTransport: insecure-skip-verify
