---
apiVersion: v1
kind: Service
metadata:
  name: adguard-02
  namespace: internal-services
spec:
  type: ExternalName
  externalName: 192.168.95.12
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-02-ingressroute
  namespace: internal-services
  annotations:
    kubernetes.io/ingress.class: traefik-internal
    uptime-kuma.autodiscovery.probe.name: "AdGuard Home 02"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`adguard-02.clsn.dev`)
      kind: Rule
      services:
        - name: adguard-02
          port: http
          scheme: http
          serversTransport: insecure-skip-verify
