apiVersion: v1
kind: Secret
metadata:
    name: mongodb-ops-manager-secret
    namespace: notesnook
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:Vd+V0OENB6c=,iv:+7C2cADvHRnHgZGWvDGWPLaWp2wMWwgo8Rzw6+7fZmU=,tag:3B8YAw0E+Z2aoN52I5RHCw==,type:str]
    publicApiKey: ENC[AES256_GCM,data:miXdJQva719320vkyMQj6kGsJxQIC0JXmOAJGXuMusM+THL3,iv:mqtLSjObg8ESPpSchY4CJuzEJvta+tgOz1HPDTEuLKI=,tag:TKSYYdmi+sDkdIf6rI1xDg==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZd1g1MmU2MmNnSjE3ajNp
            Znoyd3JzV1ZITFhVb0tzQnR5cUR5cFVnRWg4Citvb1I5blE4alVaOFVSY2p1d3hQ
            bXJQeWhta0FQckJhZDlwSUljM2VEY2MKLS0tIHlxeDAyYUhIWGMzL1dQQ1FGeWZS
            UENBbmZnUkxRZlVXZkh6eGRQMktxNkEKuZirDwGCuDu+ZyBrbncvqovIl8QE8Z/z
            0L92K0kF9qBoOXQec48Z/zT2xeWDPa4pW7/mdyfA8O/cnWworluexQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T00:44:19Z"
    mac: ENC[AES256_GCM,data:aZupESZnTBd7aurY6vuhDXtyTDzkFchuOalKIjNaevrY7X7ftcEeLTGCjwQ/ZH/2euN2NQ8+cwvg7apk04jULjourlMODii0VCU2vb78FPFCZXT+OcgcLS22T9gg3RBIZpzOf5no+SvAlN0Li/JRoJeWCvLCweAmN0MSAKRI/m8=,iv:BLUZmn0BiD+bHuwGiSfShYPMp08u2aNcLMXOffbU4I4=,tag:+IcxVl2CoPKii4yAoECkwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
