apiVersion: v1
kind: Secret
metadata:
    name: notesnook-env-secret
    namespace: notesnook
type: Opaque
stringData:
    INSTANCE_NAME: ENC[AES256_GCM,data:oS9/n/JDyHH7iP/fRVg=,iv:0lCRA9jQKckytOxUvRFAPZOzbJRBGPlRCaDgcquLa/o=,tag:xnAjk0kf6ZPU42pzd8qFQw==,type:str]
    NOTESNOOK_API_SECRET: ENC[AES256_GCM,data:+TQjzIHj3KUTrrkw5s1+xL3A4pthFEWlI5V5ko1otd56KcJxeXGJapr0kvs=,iv:rHvdL26jwWlh2c6E0K7h4MFGT2FSIsQW/GathIKD9/4=,tag:3e+Q/OQT98itvVdJSPFWDw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:iHj+vINb9pA2m24k/JZd,iv:yYEj2S4gZ/cJODHZGSgJiZp0nHw4VV5etCbONm542t4=,tag:/ioCU0zgkkJKYL4lbZI/ww==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:F0GHjQLffyxe8vVDE7pTjw==,iv:UtD0hdnHNYV/1ypPufDXPJEyQyBFcGSB6AwznxzBEZY=,tag:yA1cTFL/yyC3Bw1gy4LZfQ==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:oKJYrpUUh6NgV3yAl84RFGDH,iv:ushwz0Yk9O6zINnTYPyqwmSPQByiYkAPgi35APcIFaI=,tag:3/kckcrystPP2ns4Eor46w==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:J/QP,iv:MJ8q++rh4U+F20xLY+7atErwr/P8dwKAhtLTibCwmpQ=,tag:gnge5YyZUO6FPbpRt/coQQ==,type:str]
    NOTESNOOK_SENDER_EMAIL: ENC[AES256_GCM,data:1rsOek55C+zA5VpMxDxi,iv:VGC2VU+MEfxDXPUVt/zpDot4gYVLydws3JCy8K4FIwk=,tag:TAMZFk0w2T5zo9PtIAtpCQ==,type:str]
    SMTP_REPLYTO_EMAIL: ENC[AES256_GCM,data:iOlti0/f/Qi40YOycvbl,iv:YDt716EAOr65WxeEjsCryALEQd0/n4fg4KyHDnYR1ig=,tag:2VPezDo0go3z1MsvMptO7Q==,type:str]
sops:
    age:
        - recipient: age1p9wexc38fk79fuwlucwneq9j8sanq0x80ezjmun8uvlvfdajza5s46pccu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcGtuMGVHNnQwemhzejhq
            TEhSblZJaUdYejdiNHRHVWtFSVpaQUt2anhnCm5NR2J5NzlYMThOaVVlRmUrdlda
            Nkh3UmU3QUVSUlZIOTVxZ1dzVlhHcGMKLS0tIEc2TlBpWkV4M1NOWmpFMlRNNEl3
            cFZIT3FCcHJhbm9BV0grajlDWWtzRmcKmurTuT6u6GShtUhH7nulvZ+SSk+jE8lq
            VKHVRE3ZMu6YcPSIP7y9nb9K7lvqBLIsBFy7aQVZAvfLKj9JRIHyJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T01:38:36Z"
    mac: ENC[AES256_GCM,data:S3Z0VtIrQ9+m7WqIKLhL+6PiSYLM7Up24DpY0TVZRi1otNuAuxzu9jArIyObEjOMUOeGo82XotXRccQWFjMTd5wSWT9M0GIPDwhwJOwXfO6pknVmdtvJZBc3WqzgP1GpdKgLw9vuQNqgfGIhvjfeF8sQYJtIzscz2ATxMcVp3l0=,iv:Rm8IaslhK6Q8zXTSSMaJUUFLLZ+RWizzmv+JBW2awJ0=,tag:ky9lARp5h6fOf3G4y2cWiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
